from .static import StaticGroupLinearFunction, OptimizedGroupLinearFunction, OptimizedContinuousLinearFunction
from .random_semisync import RandomGroupLinearFunction, RandomSequentialFunction
from .stochastic_semisync import StochasticGroupLinearFunction
from .random_conv2d import RandomConv2dSemiSyncFuncion
