from .static import GroupLinearFunction, SequentialLinearFunction
from .random_semisync import RandomGroupLinearFunction, RandomSequentialFunction
from .stochastic_semisync import StochasticGroupLinearFunction
from .random_conv2d import RandomConv2dSemiSyncFuncion
